# config/watchlists.yaml
# Things we explicitly care about. Empty by default.

tickers: []
# Example:
# tickers:
#   - AAPL
#   - NVDA

cik: []
# Example:
# cik:
#   - "0000320193"  # Apple Inc.

crypto: []
# Example:
# crypto:
#   - BTC
#   - ETH
